### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#1]
A login screen for users

Use png for now, eventually this will be switched to svg

Mobile View: 
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/3bac47b4-6b82-48bd-8d4e-782094314fe9)

Desktop View: Just ensure it takes the full screen

Taken By: Dafne G

**Comment by KingJordan152** [comment]
Blocked by #4 and #5.
