### ISSUE TITLE
Implement Backend Functionality to the Registration Page

### ISSUE THREAD

**Issue by KingJordan152** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#108]
The client side of the registration page has been completed in #104 thanks to @RedPenguin88. However, we still need to incorporate the actual functionality for adding the newly created user to the database and navigating them to the Home page.

This feature should be added to the `handleCreateAccount` function in `Register.tsx`. You should use the `useCreateUserMutation` hook from the `@/store` directory. This will provide you with a function that stores the new user's information in the database.

Here's an example of how you can do this:

```tsx
const [createUser] = useCreateUserMutation();
...
const handleCreateAccount = () => {
    createUser({...})
}
```

# Acceptance Criteria
- Use the `useCreateUserMutation` hook to add a new user to the database.
- Incorporate the logic in `Register.tsx`.
- Navigate the user to the Home page if the request to create a new user was successful.
- Handle failed requests appropriately.

# Helpful Resources
- https://redux-toolkit.js.org/rtk-query/usage/mutations

**Comment by KingJordan152** [comment]
@RedPenguin88 you can pick this up since you built the Registration sequence, if you want.

**Comment by RedPenguin88** [comment]
Sure, that sounds alright.
