### ISSUE TITLE
Style Audit: `Navbar` Style Update

### ISSUE THREAD

**Issue by KingJordan152** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#127]
# Description

Currently, the bottom navigation component we use doesn't stylistically match the rest of the site. It uses blue buttons and a font that isn't used anywhere else.

Please update this component to match the design language that we've established for the rest of the site.

# Acceptance Criteria

- [ ] Update the buttons on the `Navbar` to use the same color of orange that's used throughout the rest of the site.
- [ ] Make sure the font is either Roboto or Open Sans (see #126)

Feel free to make other changes that would either increase the contrast of the buttons or the `Navbar` itself. If you're ensure about the design, ask in your PR and we'll assess it.

# Help

Here are the docs for MUI's `BottonNavigation` component, which `Navbar` uses under the hood: https://mui.com/material-ui/react-bottom-navigation/

**Comment by trevortippery** [comment]
I will take on this task.
