### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#2]
Create a loading screen to display over the app when going to a new section

Use png for now, eventually this will be switched to svg

Mobile View:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/7f7b7063-e04d-4c1a-b4de-e30006a6f998)

Desktop View:
Blow up image and center it

**Comment by trevortippery** [comment]
Where would the best place be for this loading page to be in? Another directory in pages or would it be better off in components?

**Comment by Linkaloo** [comment]
Make it a component because the purpose is that it overlays on the page that is currently loading and then once that page loads it gets removed. So you don't want to route to a page then route to this loading page then route back to the page you wanted
