### ISSUE TITLE
Reset Password - reset 

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#22]
For the reset password page. 
Make a component to enter email 
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/088f5097-5681-42ff-afab-8a258ca52c20)

**Comment by trevortippery** [comment]
Should I make a whole new text field component for this reset password page or use the `TextField` component that is already made?

**Comment by Linkaloo** [comment]
Use the one that already exists
