### ISSUE TITLE
Register Account - General Info

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#3]
General Info section when registering an account

Mobile View:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/fcbc9c95-4205-462a-80a2-201305359742)

Desktop:
Blow up and center

Taken By: Timok

**Comment by KingJordan152** [comment]
Blocked by #4 and #5.
