### ISSUE TITLE
Home Page - Add Map

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#34]
This is a very difficult issue.
Only need to change client.
The goal is to just add a simple map to the home page.
Probably using some api, maybe google maps api.
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/a2808892-6773-4a51-be49-16404f2ba552)

**Comment by tbmcallister** [comment]
Probably a useful article
https://medium.com/@alvinwquach/implementing-google-maps-in-a-react-component-with-typescript-da2d2d3ac51d

**Comment by tbmcallister** [comment]
https://www.geeksforgeeks.org/how-to-add-google-maps-to-a-website/amp/

**Comment by tbmcallister** [comment]
https://mapsplatform.google.com/pricing/

**Comment by morenj** [comment]
Hey @tbmcallister is it alright if I take this issue from you? 

I have already added a map implementation on the Home page as a component that can be used crossed the app. 

Sorry, I did not notice this sooner or I would have claimed it earlier.
