### ISSUE TITLE
Post Data Model

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#48]
Server issue
We need a way to store posts related to a community.
MongoDB does support One-To-Many relationships and this would be when to use them.
We have a task to make a community model, now we need a model for posts so we can store and retrieve posts.
A post should have:
- Person that created it
- Like count
- Type of post (we support 2 types)
- content of the post
- marker type
- the community it belongs to (This would be a foreign key tied to the community model)

There will be a one to many relationship where 1 community can have many posts

**Comment by Linkaloo** [comment]
I'm gonna say add that a post has a user associated to this as well

**Comment by Aligary** [comment]
I think a Post 'time created/posted' would be useful

**Comment by Aligary** [comment]
Also, if it is a marker post, we should have the actual marker? this way we can display where on the map it is using the location.
