### ISSUE TITLE
Register Account - Location

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#6]
Create the component for Location for register account screen

Ignore the drop down aspect

Mobile View:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/d78ce2d8-296b-45f6-8b49-ef96fa3dbbb5)

Desktop View:
Blow up and center

**Comment by KingJordan152** [comment]
Blocked by #4 and #5.
