### ISSUE TITLE
Register Account - Create Account

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#7]
Create the final component for the Register Account screen

Wait on Aligary for password component

Mobile View:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/96d70bca-ea82-4043-aaee-088562a7c247)

Desktop View:
Blow up and Center

**Comment by KingJordan152** [comment]
Blocked by #4
