### ISSUE TITLE
Instructions Page

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#8]
Add a new page for instructions.
3 images and descriptions horizontal scroll container.
Details TBD but use your judgement for now

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/a5348dda-1145-4bca-9e31-d22063513764)

**Comment by KingJordan152** [comment]
Blocked by #4.
