### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Linkaloo** [UNLV-CS472-672/2024-S-GROUP1-Roadwatch#9]
Keep this page very simple right now.

Ignore:
- map view
- filters
- add marker button

Add:
- Top component with welcome (ignore active)
- - notif panel and help panel do nothing
- Navigation
- - Someone else will work on these but please add them once they finish
- - Bottom nav component (Mobile View) 
- - Top nav component (Desktop View)

Mobile View:
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/24483977/90e581c8-f3c3-4da0-91cd-f03b948a2110)

Taken By: JuanM

**Comment by morenj** [comment]
Current progress on the Home page. 

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/assets/56707302/ce196b4c-f5d6-479f-b9cf-1a9554fc3f83)
